version: "3.9"

services:
    db:
        image: flobbe10/myairline-db:0.0.1
        container_name: myairline-db
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_DATABASE: myAirline
            MYSQL_ROOT_PASSWORD: mysql