version: "3.9"
services:
    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_DATABASE: myAirline
            MYSQL_ROOT_PASSWORD: mysql