name: myAirline
run-name: ${{ github.event.head_commit.message }}
on: [push]
jobs:
  Push_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2.5.1
        with: 
          distribution: 'temurin'
          java-version: '17'
      - run: docker-compose up -d
      - run: gradle clean build